### PR TITLE
use list in install_adapters()

### PR DESCRIPTION
**Pull request by fambon**

### CODE REVIEW

**Review by abr-ubiqube — CHANGES_REQUESTED** [review]
Hello @fambon 
You need to use BR 2.3.0GA as the dev branch and PR into ubiqube:2.3.0GA

**Comment by fambon** [comment]
changes done on 2.3.0GA in #51

**Comment by abr-ubiqube** [comment]
@fambon 
I guess this one is a dup of https://github.com/ubiqube/quickstart/pull/51 (which is merged) ?

**Comment by fambon** [comment]
this is a _port_ to master - or actually, the original contribution, which I ported to 2.3.0 GA in #51 upon your request.

**Comment by abr-ubiqube** [comment]
> this is a _port_ to master - or actually, the original contribution, which I ported to 2.3.0 GA in #51 upon your request.

yes, so we can close this PR since the BR2.3.0 will be merged on master when 2.3 is released (mid-January)

**Comment by fambon** [comment]
I pushed the rebased PR on top of the current master - which seems to welcome many kind of commits - so it can be merged; or ignored.

**Pull request closed without merging**
