### PR TITLE
fix missing tt for ssh

### PR DESCRIPTION
**Pull request by efeubiqube**

### CODE REVIEW

**Review by abr-ubiqube — COMMENTED** [review]
@efeubiqube 
seems that "-o BatchMode=Yes" is also missing

**Comment by efeubiqube** [comment]
> @efeubiqube seems that "-o BatchMode=Yes" is also missing

Should I add? It was missing before

**Comment by abr-ubiqube** [comment]
> > @efeubiqube seems that "-o BatchMode=Yes" is also missing
> 
> Should I add? It was missing before

I'm not sure it's needed, even for the previous calls to ssh, since the scripts request auth with ssh key anyway

**Review by abr-ubiqube — APPROVED** [review]

**Comment by abr-ubiqube** [comment]
@efeubiqube 
looks like "-o BatchMode=Yes" is also needed because the install failed with the same error

**Pull request merged**
